class Product{
  Product();
  List<Autogenerated> autos =[];
  Product.fromJson(List<dynamic>json)
  {
    json.forEach((element) {
      autos.add(new Autogenerated.fromJson(element));
    });
  }
}
class Autogenerated {
  dynamic price = 0  , id =0;
  String title ='';
  String description= '';
  String category ='';
  String image ='';
  bool in_fav = false;
  bool in_cart =false;
  int qunatity = 0;
  Rating rating =new Rating();

  Autogenerated();

  Autogenerated.fromJson(Map<String,dynamic> json) {
    id = json['id'];
    title = json['title'];
    price = json['price'];
    description = json['description'];
    category = json['category'];
    image = json['image'];
    rating =
    json['rating'] != null ? new Rating.fromJson(json['rating']) : new Rating();

  }
  Autogenerated.fromprefrence(Map<String,dynamic> json) {
    id = json['id'];
    title = json['title'];
    price = json['price'];
    description = json['description'];
    category = json['category'];
    in_fav = json['in_fav'];
    in_cart = json['in_cart'];
    qunatity = json['qunatity'];
    image = json['image'];

    rating =
    json['rating'] != null ? new Rating.fromJson(json['rating']) : new Rating();

  }
  tojson()
  {
    return {
        'id':id,
      'title':title,
      'price':price,
      'description':description,
      'category':category,
      'image':image,
      'in_fav':in_fav,
      'in_cart':in_cart,
      'qunatity':qunatity,
      'rating':{
          'rate':rating.rate,
           'count':rating.count
      }
    };
  }

}

class Rating {
  Rating();
  dynamic rate =0.0,count =0;


  Rating.fromJson(Map<String, dynamic> json) {
    rate = json['rate'];
    count = json['count'];
  }

}
